In [16]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

from ulmo import io as ulmo_io

In [7]:
tbl = pd.read_parquet('/home/jovyan/ulmo/ulmo/tests/ulmo2_test.parquet')
tbl.head()

,modis_lat,modis_lon,modis_col,modis_datetime,modis_LL,modis_row,clear_fraction,mean_temperature,Tmin,Tmax,...,field_size,pp_type,pp_idx,lat,lon,row,col,datetime,filename,LL
0,-52.410507,-42.126858,1028,2012-01-01 04:10:00,-147.370605,64,0.049805,4.126851,3.401999,6.411,...,64,0,296266,-52.406319,-42.135418,4687,17049,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...,127.225403
1,-52.194720,-42.787216,997,2012-01-01 04:10:00,-248.946106,48,0.043213,5.315916,3.464000,6.544,...,64,0,592057,-52.188812,-42.781250,4705,17018,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...,53.644531
2,-52.031720,-43.191420,976,2012-01-01 04:10:00,-264.156342,33,0.049500,5.914161,3.557000,6.852,...,64,0,214472,-52.031147,-43.197918,4718,16998,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...,161.347656
3,-51.908875,-42.702328,997,2012-01-01 04:10:00,-228.816925,16,0.018188,5.859090,3.442000,6.709,...,64,0,467098,-51.909538,-42.697918,4728,17022,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...,172.184753
4,-51.865665,-43.186947,974,2012-01-01 04:10:00,-260.829315,16,0.048279,6.130058,5.386000,6.852,...,64,0,415175,-51.860813,-43.177082,4732,16999,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...,156.553528

In [14]:
tbl1 = tbl.drop( columns = ['LL'])

In [19]:
tbl1.head()

,modis_lat,modis_lon,modis_col,modis_datetime,modis_LL,modis_row,clear_fraction,mean_temperature,Tmin,Tmax,...,pp_root,field_size,pp_type,pp_idx,lat,lon,row,col,datetime,filename
0,-52.410507,-42.126858,1028,2012-01-01 04:10:00,-147.370605,64,0.049805,4.126851,3.401999,6.411,...,llc_std,64,0,296266,-52.406319,-42.135418,4687,17049,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...
1,-52.194720,-42.787216,997,2012-01-01 04:10:00,-248.946106,48,0.043213,5.315916,3.464000,6.544,...,llc_std,64,0,592057,-52.188812,-42.781250,4705,17018,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...
2,-52.031720,-43.191420,976,2012-01-01 04:10:00,-264.156342,33,0.049500,5.914161,3.557000,6.852,...,llc_std,64,0,214472,-52.031147,-43.197918,4718,16998,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...
3,-51.908875,-42.702328,997,2012-01-01 04:10:00,-228.816925,16,0.018188,5.859090,3.442000,6.709,...,llc_std,64,0,467098,-51.909538,-42.697918,4728,17022,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...
4,-51.865665,-43.186947,974,2012-01-01 04:10:00,-260.829315,16,0.048279,6.130058,5.386000,6.852,...,llc_std,64,0,415175,-51.860813,-43.177082,4732,16999,2012-01-01,s3://llc/ThetaUVSalt/LLC4320_2012-01-01T00_00_...

In [21]:
tbl1.pp_file = 's3://llc/PreProc/LLC_modis2012_SST_noise_demean_preproc.h5'

In [23]:
tbl1.pp_file

0         s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
1         s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
2         s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
3         s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
4         s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
                                ...
635290    s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
635291    s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
635292    s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
635293    s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
635294    s3://llc/PreProc/LLC_modis2012_SST_noise_demea...
Name: pp_file, Length: 635295, dtype: object

In [24]:
ulmo_io.write_main_table(tbl1, 's3://llc/Tables/ulmo2_test.parquet')

Wrote Analysis Table: s3://llc/Tables/ulmo2_test.parquet